// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailsIcon': string;
  'event': string;
  'folder': string;
  'monitor': string;
  'qualityProfile': string;
  'seasonFolder': string;
  'seriesType': string;
}
export const cssExports: CssExports;
export default cssExports;
